#!/usr/bin/env python
# -*- coding: utf-8 -*-

import os

d = '/Applications/GitKraken.app/Contents/Resources'
if not os.path.isdir(d):
    print("GitKraken 尚未安装")
    exit(-1)

print("切换目录到 %s..." % d)
os.chdir(d)
if os.path.isdir(d + "/unpacked"):
    os.system("rm -rf " + d + "/unpacked")

# 解压
print("解压 app.asar...")
os.system("cp app.asar app.asar.bak")
os.system("asar e app.asar unpacked")

# 替换文件
print("替换文件...")
f = open(d + "/unpacked/static/clientType.js", mode='wb')
content = """// This file is auto-generated by the set-client-type.js script
module.exports = 'development';
"""
f.write(bytes(content))
f.close()

# 重新打包
print("重新打包...")
os.system("rm app.asar && asar pack unpacked app.asar")

# 清理操作
os.system("rm -rf unpacked")

print("破解成功!")

# 打开 Gitkraken
script = """tell application "GitKraken"
    activate
    # set frontmost to true

    try
        set miniaturized of windows to false -- most apps
    end try
end tell"""
os.system("osascript -e '%s'" % script)
